### ISSUE TITLE
Updates to website homepage

### ISSUE THREAD

**Issue by austinkocher** [RelevantResearch/michael-paarlberg#7]
## Here is the title now:
"Michael A. Paarlberg
Assistant Professor of Political Science at Virginia Commonwealth University"
(The text is fine)

## Fix left alignment on mobile
The subtitle ("Assistant Professor...") flows left of the margin when on mobile (see screenshot attached).

## Align with menu
The subtitle doesn't align well with the navigation menu on the right. Let's try to fix this (see screenshot attached). 

## Suggestion: reduce text size of subtitle
It might help to reduce the text size of the subtitle, I'm not sure.

## Suggestion: center the heading? 
I drafted a possible version of the header of the website that might work, but please advise on your thoughts about this design and whether it is feasible.

## Suggestion: change title font to Gill Sans
It might work to change the title font to Gill Sans bold and have the subtitle in Gill Sans italics, and the menu bar in Gill Sans plain. Maybe use Gill Sans for the headings, too? Just a thought, please let me know what you think.

## Capitalize menu bar
Capitalize all words in the menu navigation bar.

## Change menu bar names
Change pages to the names (in order): 
- About
- Media
- Publications
- Teaching
- Consulting

## Change headings to same as pages
Create five headings on the page (in order, starting from the top):

- About
- Media
- Publications
- Teaching
- Consulting

## Add footer
Add a footer at the bottom that uses are normal style (copywriter, client name, Relevant Research, etc.)

## Images and Drafts
![image](https://github.com/user-attachments/assets/28873747-8362-4b11-8007-496558e3abb5)
![image](https://github.com/user-attachments/assets/2714f801-b11d-440e-a45e-35a78a49bdea)
![image](https://github.com/user-attachments/assets/c3e5d731-931d-42d6-9a63-918b8d336bae)
![image](https://github.com/user-attachments/assets/9650ddb9-1c25-4941-b52e-8d4f278aa504)

**Comment by SandeshNilasKhatiwada** [comment]
## Alignment Issue  Solved
![Screenshot 2024-09-16 at 10 34 13 PM](https://github.com/user-attachments/assets/fd052b03-75d4-4cdf-9cbf-3602380960d8)
 and since I have divided the description section to row I aligned nav bar to the top 

## Footer Section 
![Screenshot 2024-09-16 at 10 43 23 PM](https://github.com/user-attachments/assets/fb53975c-8e27-4f6a-ae7f-e73f72aa060b)
for now just created the footer section like this 

## changes in mobile view 
![Screenshot 2024-09-16 at 10 42 20 PM](https://github.com/user-attachments/assets/6ecdd378-32a4-4fb0-993d-6db9e7990bdb)
since we have to slide the nav bar so I went for this approach to make the nav bar in row
